name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes: { label: Problem to solve, placeholder: What’s missing / painful? }
  - type: textarea
    id: proposal
    attributes: { label: Proposal, placeholder: What should HomelabFlix do? UI mock? }

