
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          # Install base dependencies first
          cd client
          npm install recharts@3.1.2 --save-exact
          # Now install remaining dependencies
          npm install
          cd ../server
          npm install
      - name: Typecheck client
        working-directory: client
        run: npx tsc --noEmit -p tsconfig.json
      - name: Lint client
        run: |
          cd client
          npm run lint || npx eslint .
      - name: Build client
        run: |
          cd client
          npm run build
      - name: Build server
        run: |
          cd server
          npm run build
